server:
  port: 8081

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.184:8848

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"



