server:
  port: 9092

spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.185:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:8080


feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"



