server:
  port: 9092

spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.184:8848


feign:
  sentinel:
    enabled: true

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"



