server:
  port: 9091

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.184:8848

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"



